apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: site-persike
resources:
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - infisical-zot.yaml
images:
  - name: 127.0.0.1:30500/meusite
    newTag: prod-2b40dcd473e82c8d0c9ca8f534ccee05530f9131-35974549645-1
    digest: sha256:352b150a6e0c6ee8edc11c7e27f267de6ed7dd0b4778458b6bd71d0bf36228ca
